[package]
name = "docs-search-desktop"
version = "2.0.3"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
docs-search-core = { path = "../core" }
open = "5"
rfd = "0.16"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.12", features = [] }
